"""Dataset adapters. Every loader returns a Dataset with: X (descriptors / features), y, task,
groups (scaffold or None), fp (bool fingerprints or None), name, domain."""
from dataclasses import dataclass
from typing import Optional
import numpy as np


@dataclass
class Dataset:
    name: str
    domain: str
    task: str                      # 'classification' | 'regression'
    X: np.ndarray
    y: np.ndarray
    groups: Optional[np.ndarray] = None
    fp: Optional[np.ndarray] = None
    prefeaturized: bool = False
    meta: Optional[dict] = None


MOL_DESCRIPTORS = ["MolWt", "MolLogP", "TPSA", "NumHDonors", "NumHAcceptors", "NumRotatableBonds",
                   "RingCount", "NumAromaticRings", "FractionCSP3", "HeavyAtomCount", "LabuteASA",
                   "NumHeteroatoms"]


def _mol_features(smiles, n_bits=2048):
    from rdkit import Chem, RDLogger
    from rdkit.Chem import Descriptors, rdFingerprintGenerator
    from rdkit.Chem.Scaffolds import MurckoScaffold
    RDLogger.DisableLog("rdApp.*")
    gen = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=n_bits)   # ECFP4
    X, F, S, keep = [], [], [], []
    for k, smi in enumerate(smiles):
        m = Chem.MolFromSmiles(smi)
        if m is None:
            continue
        X.append([getattr(Descriptors, d)(m) for d in MOL_DESCRIPTORS])
        F.append(gen.GetFingerprintAsNumPy(m).astype(bool))
        S.append(MurckoScaffold.MurckoScaffoldSmiles(mol=m) or "acyclic")
        keep.append(k)
    uniq = {s: i for i, s in enumerate(sorted(set(S)))}
    return np.array(X, float), np.array(F), np.array([uniq[s] for s in S]), np.array(keep)


def load_delaney(path="data/delaney-processed.csv"):
    import pandas as pd
    d = pd.read_csv(path)
    X, F, G, keep = _mol_features(d["smiles"].tolist())
    y = d["measured log solubility in mols per litre"].values[keep]
    return Dataset("delaney_esol", "molecules", "regression", X, y.astype(float), G, F)


def load_garg_target(csv_path, target, threshold, max_rows=None):
    """Garg & Garg (2026) data.csv (Git LFS; download separately). Binary label: pIC50 >= threshold."""
    import pandas as pd
    d = pd.read_csv(csv_path, usecols=["protein", "SMILES", "pIC50"])
    d = d[d.protein == target]
    if max_rows:
        d = d.sample(min(max_rows, len(d)), random_state=0)
    X, F, G, keep = _mol_features(d["SMILES"].tolist())
    y = (d["pIC50"].values[keep] >= threshold).astype(int)
    return Dataset(f"garg_{target}_{threshold}", "molecules", "classification", X, y, G, F)


def load_csv_molecules(path, smiles_col, label_col, task, name=None):
    import pandas as pd
    d = pd.read_csv(path)
    X, F, G, keep = _mol_features(d[smiles_col].tolist())
    y = d[label_col].values[keep]
    return Dataset(name or path, "molecules", task, X, y, G, F)


def load_tdc(name, group="ADMET_Group"):
    """Needs `pip install PyTDC` and network access to the TDC data host (not available in all sandboxes)."""
    from tdc.single_pred import ADME, Tox
    try:
        d = ADME(name=name).get_data()
    except Exception:
        d = Tox(name=name).get_data()
    X, F, G, keep = _mol_features(d["Drug"].tolist())
    y = d["Y"].values[keep]
    task = "classification" if set(np.unique(y)) <= {0, 1} else "regression"
    return Dataset(f"tdc_{name}", "molecules", task, X, y, G, F)


def load_sklearn(name):
    from sklearn import datasets as sd
    if name == "breast_cancer":
        b = sd.load_breast_cancer(); return Dataset("sk_breast_cancer", "clinical_tabular", "classification", b.data, b.target)
    if name == "wine":
        b = sd.load_wine(); y = (b.target == 0).astype(int); return Dataset("sk_wine", "chemometrics", "classification", b.data, y)
    if name == "diabetes":
        b = sd.load_diabetes(); return Dataset("sk_diabetes", "clinical_tabular", "regression", b.data, b.target.astype(float))
    raise ValueError(name)


def synthetic_control(kind, n_features=8, n_total=800, seed=0, bandwidth=0.3, n_anchor=40, edges="linear", reps=1):
    """Positive/negative controls whose labels are generated by a known kernel model.
    kind='quantum' -> labels from a ZZ fidelity-kernel model (positive control: quantum SHOULD win/tie).
    kind='classical' -> labels from an RBF model (negative control: quantum should NOT win)."""
    from .kernels import fidelity_gram, rbf_gram
    rng = np.random.default_rng(seed)
    X = rng.uniform(-1, 1, (n_total, n_features))
    Z = rng.uniform(-1, 1, (n_anchor, n_features)); a = rng.normal(size=n_anchor)
    if kind == "quantum":
        f = fidelity_gram(X, Z, reps=reps, bandwidth=bandwidth, edges=edges) @ a
    else:
        f = rbf_gram(X, Z, gamma=1.0 / n_features) @ a
    y = (f > np.median(f)).astype(int)
    nm = f"synthetic_{kind}" + ("" if (bandwidth == 0.3 and n_anchor == 40) else f"_bw{bandwidth}_a{n_anchor}")
    return Dataset(nm, "synthetic_control", "classification", X, y)


def get_dataset(spec):
    """spec examples: delaney | sk:breast_cancer | syn:quantum | garg:/path/data.csv:BACE1:7.0 | tdc:Caco2_Wang"""
    if spec == "delaney":
        return load_delaney()
    kind, _, rest = spec.partition(":")
    if kind == "eng":   # eng:<base spec>[@bandwidth]   e.g. eng:delaney@0.3  or eng:sk:wine
        # eng:<base>[@bandwidth[@rivals]]   rivals in {rbf, rbf+lap, all}
        parts = rest.split("@"); base = parts[0]
        return engineered_advantage(base, bandwidth=float(parts[1]) if len(parts) > 1 else 0.3,
                                    rivals=parts[2] if len(parts) > 2 else "rbf")
    if kind == "sk":
        return load_sklearn(rest)
    if kind == "syn":   # syn:quantum | syn:classical | syn:quantum:<bandwidth>:<n_anchor>
        parts = rest.split(":")
        return synthetic_control(parts[0], bandwidth=float(parts[1]) if len(parts) > 1 else 0.3,
                                 n_anchor=int(parts[2]) if len(parts) > 2 else 40)
    if kind == "garg":
        p, t, thr = rest.rsplit(":", 2); return load_garg_target(p, t, float(thr))
    if kind == "tdc":
        return load_tdc(rest)
    raise ValueError(spec)


def engineered_advantage(base="sk:wine", n_points=240, n_qubits=8, reps=1, edges="linear", bandwidth=0.3,
                         lam=1e-3, seed=0, binarize=True, rivals="rbf"):
    """Huang-style engineered-advantage control on REAL input features.
    Labels are built so that (i) the target has quantum-RKHS norm 1 and (ii) its RKHS norm w.r.t. the SUM of a whole
    classical kernel family (RBF + Laplacian + metric-twin over a gamma grid) equals g_sum^2 (>= the norm w.r.t. each member).
    See blueprint Theorem T4. This is advantage BY CONSTRUCTION against that family, not evidence about real data."""
    from sklearn.preprocessing import StandardScaler
    from sklearn.decomposition import PCA
    from .kernels import fidelity_gram, rbf_gram, laplacian_gram, twin_gram
    ds = get_dataset(base); rng = np.random.default_rng(seed)
    idx = rng.choice(len(ds.y), size=min(n_points, len(ds.y)), replace=False)
    Z = StandardScaler().fit_transform(ds.X[idx]); Z = PCA(n_components=n_qubits, random_state=0).fit_transform(Z)
    Z = Z / (np.abs(Z).max(0) + 1e-9)
    Kq = fidelity_gram(Z, reps=reps, edges=edges, bandwidth=bandwidth)
    gam = np.logspace(-2.5, 1.0, 12) / n_qubits
    parts = {"rbf": lambda g: rbf_gram(Z, Z, g), "lap": lambda g: laplacian_gram(Z, Z, g), "twin": lambda g: twin_gram(Z, Z, g, edges=edges)}
    use = {"rbf": ["rbf"], "rbf+lap": ["rbf", "lap"], "all": ["rbf", "lap", "twin"]}[rivals]
    Kc = sum(parts[k](g) for g in gam for k in use)
    nk = len(gam) * len(use)
    w, V = np.linalg.eigh((Kq + Kq.T) / 2); S = (V * np.sqrt(np.clip(w, 0, None))) @ V.T
    A = np.linalg.inv(Kc + lam * np.eye(len(Z)))
    M = S @ A @ S; ev, EV = np.linalg.eigh((M + M.T) / 2); v = EV[:, -1]
    f = S @ v
    y = (f > np.median(f)).astype(int) if binarize else f
    g_sum = float(np.sqrt(ev[-1]))
    Mn = len(Z); Kc_n = Kc * (Mn / np.trace(Kc)); Kq_n = Kq * (Mn / np.trace(Kq))
    w2, V2 = np.linalg.eigh(Kq_n); S2 = (V2 * np.sqrt(np.clip(w2, 0, None))) @ V2.T
    g_norm = float(np.sqrt(np.linalg.norm(S2 @ np.linalg.inv(Kc_n + lam * np.eye(Mn)) @ S2, 2)))
    return Dataset(f"eng_{base.replace(':', '_')}_{rivals}_bw{bandwidth}", "engineered_control", "classification" if binarize else "regression",
                   Z, y, None, None, prefeaturized=True,
                   meta={"g_sum_raw": g_sum, "n_kernels_in_sum": nk, "g_trace_normalised": g_norm, "g_over_sqrtN": g_norm / np.sqrt(Mn), "n_points": Mn, "f": f})
